import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="py-4">
          <div className="container mx-auto">
            <div className="flex items-center gap-5">
              <Link href={"/"}>Product</Link>
              <Link href={"/category"}>Category</Link>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
